version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: conect_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: conect
      POSTGRES_PASSWORD: conect1234
      POSTGRES_DB: conect_app
    ports:
      - "5432:5432"
    volumes:
      - conect_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conect -d conect_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  conect_pgdata:
    driver: local
